name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      run: |
        dotnet build --configuration Release FlexLib/FlexLib.csproj /property:GenerateFullPaths=true
        dotnet build --configuration Release FlexLibTests/FlexLibTests.csproj /property:GenerateFullPaths=true
    
    - name: Test with dotnet
      run: dotnet test --no-build FlexLibTests /p:GenerateFullPaths=true /p:CollectCoverage=true /p:CoverletOutput=lcov /p:CoverletOutputFormat=lcov
    
    - name: Publish coverage report with coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: FlexLibTests/lcov.info
